#!/usr/bin/env python3
"""
preToolUse hook (Copilot CLI / Copilot cloud agent).

1. Denies any tool call that touches configuration / secret files.
2. Denies direct edits of generated API-catalogue artifacts (they must be changed through
   overrides.yaml / decisions.yaml and regenerated by the scripts).

Input: hook JSON on stdin ({toolName, toolArgs, ...} or VS Code style {tool_name, tool_input}).
Output: {"permissionDecision": "deny", "permissionDecisionReason": "..."} or {} (no opinion).
"""
import json
import re
import sys

SECRET_FILES = re.compile(
    r"(?i)(appsettings[\w.\-]*\.json|local\.settings\.json|secrets\.json|usersecrets|"
    r"(?:^|[\\/\"'\s=])\.env(?:\.[\w-]+)?\b|\.pfx\b|\.p12\b|\.pem\b|\.snk\b|(?<![\w-])[\w-]+\.key\b|"
    r"\.publishsettings\b|\.pubxml\b|launchsettings\.json|web\.config|app\.config|\.azure[\\/]|credentials\.json)")

GENERATED = re.compile(
    r"(?i)(api-catalog[\\/].*?(inventory\.json|[\\/]openapi\.yaml|1-openapi\.enriched\.yaml|2-domains-capabilities\.(json|md)|"
    r"3-entities-attributes\.(json|md)|4-duplicates-report\.(json|md)|analysis-summary\.json|validation\.json|"
    r"discovery-report\.md|regional-view(-data)?\.(html|xlsx|json)|alignment\.json|acord-alignment\.(html|xlsx)|alignment-report\.md|"
    r"approvals\.yaml|review-decisions[\w.-]*\.json|canonical-model\.(json|xlsx|md)|canonical-openapi\.(yaml|json)|"
    r"source-to-canonical-mapping\.json|CHANGELOG\.md|releases[\\/]|global-canonical[\w.-]*|global-source-mapping\.json|"
    r"style-profile\.json|canonical-viewer\.html|spec-viewer\.html))")

EDIT_TOOLS = {"edit", "create", "write", "str_replace_editor", "apply_patch", "Edit", "Write", "MultiEdit"}
SHELL_TOOLS = {"bash", "powershell", "Bash", "shell", "execute"}
SHELL_WRITE = re.compile(r"(?i)(>\s*\S|\bsed\s+-i|\btee\b|set-content|add-content|out-file|\brm\b|\bdel\b|remove-item|\bmv\b|move-item|\bcp\b|copy-item)")


def decide(payload: dict):
    tool = payload.get("toolName") or payload.get("tool_name") or ""
    args = payload.get("toolArgs", payload.get("tool_input", {}))
    if isinstance(args, str):
        try:
            args = json.loads(args)
        except Exception:  # noqa: BLE001
            pass
    text = args if isinstance(args, str) else json.dumps(args)

    m = SECRET_FILES.search(text)
    if m:
        return ("deny", f"Blocked by API-catalogue policy: '{m.group(0).strip()}' is a configuration/secret file. "
                        "API discovery never needs it - work from *.cs / *.csproj only.")
    if GENERATED.search(text):
        if tool in EDIT_TOOLS or (tool in SHELL_TOOLS and SHELL_WRITE.search(text)):
            return ("deny", "Blocked by API-catalogue policy: generated or human-approval artifact. Put the change in overrides.yaml "
                            "(discovery), decisions.yaml (analysis) or alignment-overrides.yaml (alignment) and re-run the scripts. "
                            "Approvals come only from reviewers via import_review.py.")
    return None


def main():
    try:
        payload = json.loads(sys.stdin.read() or "{}")
        d = decide(payload)
    except Exception as ex:  # noqa: BLE001  - never lock the agent out because of a parsing problem
        print(f"guard_tools: {ex}", file=sys.stderr)
        d = None
    print(json.dumps({"permissionDecision": d[0], "permissionDecisionReason": d[1]} if d else {}))


if __name__ == "__main__":
    main()
