#!/usr/bin/env python3
"""
preToolUse hook (Copilot CLI / Copilot cloud agent).

1. Denies any tool call that touches configuration / secret files.
2. Denies direct edits of generated API-catalogue artifacts (they must be changed through
   overrides.yaml / decisions.yaml and regenerated by the scripts).
3. Denies network / web / browser tools and shell commands that send data out (curl, wget, ssh, mail ...).
4. Denies any write (edit tools, or shell writes) whose content contains sensitive data: credentials, e-mail
   addresses, URLs, internal hosts / IPs, personal data (phone, card, IBAN, national ids) or client names from
   api-catalog/reference/sensitive-data.yaml (see sensitive_scan.py).

Input: hook JSON on stdin ({toolName, toolArgs, ...} or VS Code style {tool_name, tool_input}).
Output: {"permissionDecision": "deny", "permissionDecisionReason": "..."} or {} (no opinion).
"""
import json
import re
import sys
from pathlib import Path

SECRET_FILES = re.compile(
    r"(?i)(appsettings[\w.\-]*\.json|local\.settings\.json|secrets\.json|usersecrets|"
    r"(?:^|[\\/\"'\s=])\.env(?:\.[\w-]+)?\b|\.pfx\b|\.p12\b|\.pem\b|\.snk\b|(?<![\w-])[\w-]+\.key\b|"
    r"\.publishsettings\b|\.pubxml\b|launchsettings\.json|web\.config|app\.config|\.azure[\\/]|credentials\.json|sensitive-data\.ya?ml|\.npmrc|\.pypirc|\.netrc|nuget\.config)")

GENERATED = re.compile(
    r"(?i)(api-catalog[\\/].*?(inventory\.json|[\\/]openapi\.yaml|1-openapi\.enriched\.yaml|2-domains-capabilities\.(json|md)|"
    r"3-entities-attributes\.(json|md)|4-duplicates-report\.(json|md)|analysis-summary\.json|validation\.json|"
    r"discovery-report\.md|regional-view(-data)?\.(html|xlsx|json)|alignment\.json|acord-alignment\.(html|xlsx)|alignment-report\.md|"
    r"approvals\.yaml|review-decisions[\w.-]*\.json|canonical-model\.(json|xlsx|md)|canonical-openapi\.(yaml|json)|"
    r"source-to-canonical-mapping\.json|CHANGELOG\.md|releases[\\/]|global-canonical[\w.-]*|global-source-mapping\.json|"
    r"style-profile\.json|canonical-viewer\.html|spec-viewer\.html))")

NETWORK_TOOL = re.compile(r"(?i)(web|fetch|http|browser|playwright|url|search_web|navigate)")
NETWORK_CMD = re.compile(r"(?i)(?<![\w-])(curl|wget|invoke-webrequest|invoke-restmethod|iwr|irm|scp|sftp|ftp|telnet|ssh|nc|ncat|"
                         r"send-mailmessage|sendmail|mailx?|start-bitstransfer)(?![\w-])|python3?\s+-m\s+http\.server|"
                         r"\b(requests|httpx|urllib\.request|aiohttp)\b.*\b(get|post|put|urlopen)\b")
CATALOG_PATH = re.compile(r"(?i)(api-catalog|\.github[\\/](skills|agents|prompts|instructions|hooks))")


def catalog_run_active() -> bool:
    """True while an API-catalogue run marker (written by catalog_run.py) is open and younger than 12 hours."""
    import time  # noqa: PLC0415
    runs = Path(".api-catalog-runs")
    return runs.exists() and any(time.time() - f.stat().st_mtime < 12 * 3600 for f in runs.glob("*.json"))


EDIT_TOOLS = {"edit", "create", "write", "str_replace_editor", "apply_patch", "Edit", "Write", "MultiEdit"}
SHELL_TOOLS = {"bash", "powershell", "Bash", "shell", "execute"}
SHELL_WRITE = re.compile(r"(?i)(>\s*\S|\bsed\s+-i|\btee\b|set-content|add-content|out-file|\brm\b|\bdel\b|remove-item|\bmv\b|move-item|\bcp\b|copy-item)")


def decide(payload: dict):
    tool = payload.get("toolName") or payload.get("tool_name") or ""
    args = payload.get("toolArgs", payload.get("tool_input", {}))
    if isinstance(args, str):
        try:
            args = json.loads(args)
        except Exception:  # noqa: BLE001
            pass
    text = args if isinstance(args, str) else json.dumps(args)

    m = SECRET_FILES.search(text)
    if m:
        return ("deny", f"Blocked by API-catalogue policy: '{m.group(0).strip()}' is a configuration/secret file. "
                        "API discovery never needs it - work from *.cs / *.csproj only.")
    # Rules 3 and 4 apply to catalogue work only (a catalogue file is touched or a catalogue run is open),
    # so other work in the same repository is not affected.
    scoped = catalog_run_active() or bool(CATALOG_PATH.search(text))
    if not scoped:
        return None if not GENERATED.search(text) else _generated(tool, text)
    if NETWORK_TOOL.search(tool) and tool not in EDIT_TOOLS | SHELL_TOOLS:
        return ("deny", f"Blocked by API-catalogue policy: '{tool}' can send data outside the workspace. "
                        "Catalogue work uses local files and scripts only.")
    if tool in SHELL_TOOLS and NETWORK_CMD.search(text):
        return ("deny", "Blocked by API-catalogue policy: this command can send data outside the workspace "
                        "(curl / wget / ssh / mail / HTTP client). Use the skill scripts only.")
    if tool in EDIT_TOOLS or (tool in SHELL_TOOLS and SHELL_WRITE.search(text)):
        try:
            sys.path.insert(0, str(Path(__file__).resolve().parent))
            from sensitive_scan import load_policy, scan_text, summarise  # noqa: PLC0415
            found = scan_text(text, load_policy())
        except Exception:  # noqa: BLE001
            found = []
        if found:
            return ("deny", f"Blocked by API-catalogue policy: the content contains sensitive data ({summarise(found)}). "
                            "Never write e-mails, URLs, host names, keys/tokens, personal data or client names. "
                            "Describe it generically (e.g. 'contact from config', 'https://{host}') instead.")
    return _generated(tool, text) if GENERATED.search(text) else None


def _generated(tool: str, text: str):
    if tool in EDIT_TOOLS or (tool in SHELL_TOOLS and SHELL_WRITE.search(text)):
        return ("deny", "Blocked by API-catalogue policy: generated or human-approval artifact. Put the change in overrides.yaml "
                        "(discovery), decisions.yaml (analysis) or alignment-overrides.yaml (alignment) and re-run the scripts. "
                        "Approvals come only from reviewers via import_review.py.")
    return None


def main():
    try:
        payload = json.loads(sys.stdin.read() or "{}")
        d = decide(payload)
    except Exception as ex:  # noqa: BLE001  - never lock the agent out because of a parsing problem
        print(f"guard_tools: {ex}", file=sys.stderr)
        d = None
    print(json.dumps({"permissionDecision": d[0], "permissionDecisionReason": d[1]} if d else {}))


if __name__ == "__main__":
    main()
