#!/usr/bin/env python3
"""
Merge human review decisions into approvals.yaml (the only approval record the canonical-model skill trusts).

Sources
  --xlsx acord-alignment.xlsx       the review workbook (yellow decision columns)
  --json review-decisions.json      export from acord-alignment.html
Both may be given several times; later files win per row, conflicts are reported.

  python import_review.py --dir api-catalog/alignment/EU --xlsx reviewed.xlsx --reviewer "Jane Doe"
  python import_review.py --dir api-catalog/alignment/EU --json review-decisions.json

Rules
  * Empty decision cells are ignored (no change). 'pending' clears a previous decision.
  * Every recorded decision keeps reviewer, timestamp, source file and the row 'basis' (fingerprint of what was
    reviewed). If the alignment later changes that row, the approval becomes 'changed' and must be re-reviewed.
  * reject without a comment is refused.
  * This script never invents decisions. Agents must not write approvals.yaml themselves.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import sys
from pathlib import Path

import yaml

ENT = {"approve", "use-as-is", "extend", "custom", "reject", "pending"}
ATT = {"accept", "rename", "exclude", "pending"}
OPS = {"include", "exclude", "pending"}


def norm(v):
    return "" if v is None else str(v).strip()


def from_xlsx(path: Path, default_reviewer: str):
    import openpyxl
    wb = openpyxl.load_workbook(path, data_only=True)
    out = {"entities": {}, "attributes": {}, "endpoints": {}}
    spec = {
        "Entities": ("entities", {"Decision": "decision", "Reference (override)": "reference", "Canonical name": "canonicalName",
                                  "Reviewer": "reviewer", "Comment": "comment"}),
        "Attributes": ("attributes", {"Decision": "decision", "Canonical attribute name": "canonicalName",
                                      "Reviewer": "reviewer", "Comment": "comment"}),
        "Endpoints": ("endpoints", {"Decision": "decision", "Canonical path": "canonicalPath",
                                    "Canonical operationId": "canonicalOperationId", "Reviewer": "reviewer", "Comment": "comment"}),
    }
    for sheet, (kind, cols) in spec.items():
        if sheet not in wb.sheetnames:
            continue
        ws = wb[sheet]
        hdr = [norm(c.value) for c in ws[1]]
        if "ID" not in hdr:
            sys.exit(f"{path}: sheet {sheet} has no ID column - was the workbook regenerated by align.py?")
        for row in ws.iter_rows(min_row=2, values_only=True):
            rec = dict(zip(hdr, row))
            rid = norm(rec.get("ID"))
            if not rid:
                continue
            d = {v: norm(rec.get(k)) for k, v in cols.items() if norm(rec.get(k))}
            if not d.get("decision"):
                if any(k in d for k in ("canonicalName", "canonicalPath", "canonicalOperationId", "reference")):
                    d["decision"] = {"entities": "approve", "attributes": "rename", "endpoints": "include"}[kind]
                else:
                    continue
            d["basis"] = norm(rec.get("Basis"))
            d.setdefault("reviewer", default_reviewer)
            out[kind][rid] = d
    return out


def from_json(path: Path, default_reviewer: str):
    doc = json.loads(path.read_text(encoding="utf-8"))
    if doc.get("format") != "acord-alignment-review":
        sys.exit(f"{path}: not an acord-alignment review export")
    out = {"entities": {}, "attributes": {}, "endpoints": {}}
    for k in out:
        for rid, v in (doc.get(k) or {}).items():
            d = {kk: norm(vv) for kk, vv in v.items() if norm(vv)}
            if not d.get("decision"):
                if k == "attributes" and d.get("canonicalName"):
                    d["decision"] = "rename"
                elif k == "endpoints" and d.get("canonicalPath"):
                    d["decision"] = "include"
                elif k == "entities" and (d.get("canonicalName") or d.get("reference")):
                    d["decision"] = "approve"
                else:
                    continue
            d["reviewer"] = d.get("reviewer") or doc.get("reviewer") or default_reviewer
            out[k][rid] = d
    return out, doc


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", required=True, help="alignment output folder (contains alignment.json)")
    ap.add_argument("--xlsx", action="append", default=[])
    ap.add_argument("--json", action="append", default=[])
    ap.add_argument("--reviewer", default="")
    a = ap.parse_args()
    d = Path(a.dir)
    al = json.loads((d / "alignment.json").read_text(encoding="utf-8"))
    ids = {"entities": {e["id"]: e for e in al["entities"]},
           "attributes": {x["id"]: x for e in al["entities"] for x in e["attributes"]},
           "endpoints": {o["id"]: o for o in al["endpoints"]}}
    allowed = {"entities": ENT, "attributes": ATT, "endpoints": OPS}
    ap_path = d / "approvals.yaml"
    approvals = yaml.safe_load(ap_path.read_text(encoding="utf-8")) if ap_path.exists() else {}
    approvals = approvals or {}
    for k in ("entities", "attributes", "endpoints"):
        approvals.setdefault(k, {})
    approvals.setdefault("history", [])
    now = dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")
    problems, applied, cleared, conflicts = [], 0, 0, []
    batches = [(Path(x), from_xlsx(Path(x), a.reviewer)) for x in a.xlsx]
    for x in a.json:
        b, doc = from_json(Path(x), a.reviewer)
        if doc.get("alignmentGeneratedAt") and doc["alignmentGeneratedAt"] != al["meta"]["generatedAt"]:
            problems.append(f"{x}: exported from an alignment generated at {doc['alignmentGeneratedAt']}, current is "
                            f"{al['meta']['generatedAt']} - rows whose basis changed will show as 'changed'")
        batches.append((Path(x), b))
    from sensitive_scan import find_policy_file, load_policy, redact_obj, summarise
    pol, redacted = load_policy(find_policy_file(d.resolve())), []
    seen = {}
    for src, batch in batches:
        for kind, rows in batch.items():
            for rid, dec in rows.items():
                if rid not in ids[kind]:
                    problems.append(f"{src.name}: unknown {kind[:-1]} id '{rid}' - ignored")
                    continue
                if dec["decision"] not in allowed[kind]:
                    problems.append(f"{src.name}: {rid}: invalid decision '{dec['decision']}' (allowed {sorted(allowed[kind])})")
                    continue
                if not dec.get("reviewer"):
                    problems.append(f"{src.name}: {rid}: no reviewer - pass --reviewer or fill the Reviewer column")
                    continue
                if dec["decision"] == "reject" and not dec.get("comment"):
                    problems.append(f"{src.name}: {rid}: reject needs a comment")
                    continue
                if (kind, rid) in seen and seen[(kind, rid)][1] != dec["decision"]:
                    conflicts.append(f"{rid}: {seen[(kind, rid)][0]} said {seen[(kind, rid)][1]}, {src.name} says {dec['decision']} (last wins)")
                seen[(kind, rid)] = (src.name, dec["decision"])
                if dec["decision"] == "pending":
                    if rid in approvals[kind]:
                        del approvals[kind][rid]
                        cleared += 1
                    continue
                if not dec.get("basis"):
                    dec["basis"] = ids[kind][rid]["basis"]
                if kind == "entities" and dec.get("reference"):
                    cand = next((c for c in ids[kind][rid]["candidates"] if c["reference"] == dec["reference"]), None)
                    if cand:
                        dec.setdefault("source", cand["source"])
                dec, red = redact_obj(dec, pol)
                if red:
                    redacted.append(f"{src.name}: {rid}: removed {summarise(red)} from reviewer / comment fields")
                dec["at"] = now
                dec["file"] = src.name
                approvals[kind][rid] = dec
                applied += 1
    approvals["history"].append({"at": now, "files": [str(s) for s, _ in batches], "applied": applied, "cleared": cleared,
                                 "problems": len(problems)})
    approvals["region"] = al["meta"]["region"]
    approvals["slice"] = al["meta"]["scope"]["slice"]
    with open(ap_path, "w", encoding="utf-8") as f:
        f.write("# Human review decisions - written by import_review.py. Do not edit by hand; re-import a reviewed file.\n")
        yaml.safe_dump(approvals, f, sort_keys=False, allow_unicode=True, width=120)
    print(json.dumps({"approvals": str(ap_path), "applied": applied, "cleared": cleared, "conflicts": conflicts,
                      "problems": problems, "redacted": redacted,
                      "totals": {k: len(approvals[k]) for k in ("entities", "attributes", "endpoints")}}, indent=2))
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
